// Altera_avalon_temp_sensor_regs.h
// To define the names of registers that can be referred by C program.
#ifndef __ALTERA_AVALON_TEMP_SENSOR_REGS_H__
#define __ALTERA_AVALON_TEMP_SENSOR_REGS_H__
#include <io.h>
#define IORD_ALTERA_AVALON_TEMP_SENSOR_TEMPERATURE(base) IORD(base, 0)
#define ALTERA_AVALON_TEMP_SENSOR_TEMPERATURE_MSK (0xFFFFFFFF)
#define ALTERA_AVALON_TEMP_SENSOR_TEMPERATURE_OFST (0)

#define IORD_ALTERA_AVALON_TEMP_SENSOR_CONFIGURATION(base) IORD(base, 1)
#define IOWR_ALTERA_AVALON_TEMP_SENSOR_CONFIGURATION(base, data) IOWR(base, 1, data)
#define ALTERA_AVALON_TEMP_SENSOR_CONFIGURATION_MSK (0xFFFFFFFF)
#define ALTERA_AVALON_TEMP_SENSOR_CONFIGURATION_OFST (0)

#define IORD_ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_LOW(base) IORD(base, 2)
#define IOWR_ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_LOW(base, data) IOWR(base, 2, data)
#define ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_LOW_MSK (0xFFFFFFFF)
#define ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_LOW_OFST (0)

#define IORD_ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_HIGH(base) IORD(base, 2)
#define IOWR_ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_HIGH(base, data) IOWR(base, 2, data)
#define ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_HIGH_MSK (0xFFFFFFFF)
#define ALTERA_AVALON_TEMP_SENSOR_THRESHOLD_HIGH_OFST (0)
#endif 
